name: Build and merge containers

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

permissions:
  packages: write
  contents: write
  id-token: write
  attestations: write

jobs:
  build_container:
    name: Build and Push Containers
    strategy:
      fail-fast: false
      matrix:
        model: [gliner, flair, roberta, roberta_german]
        os: [blacksmith-2vcpu-ubuntu-2404, blacksmith-2vcpu-ubuntu-2404-arm]
    uses: taranis-ai/github-actions/.github/workflows/build-multiarch-bot-container.yml@master
    with:
      ghcr_image: ghcr.io/taranis-ai/taranis-natural-language-processing
      model: ${{ matrix.model }}
      os: ${{ matrix.os }}

  merge_container:
    name: Merge Container Manifests
    needs: build_container
    strategy:
      fail-fast: false
      matrix:
        model: [gliner, flair, roberta, roberta_german]
    uses: taranis-ai/github-actions/.github/workflows/merge-multiarch-bot-container.yml@master
    with:
      ghcr_image: ghcr.io/taranis-ai/taranis-natural-language-processing
      model: ${{ matrix.model }}
      latest: ${{ matrix.model == 'gliner' }}
